import type { Metadata } from "next";
import siteConfig from "@/site.config";

export const metadata: Metadata = {
  title: "About RoamPlan — AI Travel Planner & Itinerary Builder",
  description: "Learn about RoamPlan — the AI travel planner that builds personalised day-by-day itineraries, hotel picks, and local tips in seconds.",
  robots: { index: true, follow: true },
};

export default function AboutPage() {
  return (
    <main className="max-w-4xl mx-auto px-6 py-20">
      {/* Hero */}
      <div className="mb-16 fade-up">
        <div className="inline-flex items-center gap-2 px-4 py-1.5 mb-6 rounded-full border border-orange-500/30 bg-orange-900/20 text-orange-300 text-xs font-bold uppercase tracking-widest">
          <span className="w-1.5 h-1.5 rounded-full bg-orange-400 animate-pulse" />
          About Us
        </div>
        <h1 className="text-4xl md:text-6xl font-black text-white mb-6 leading-tight"
          style={{ fontFamily: "'Georgia', serif", letterSpacing: '-0.02em' }}>
          We believe travel planning<br />
          <span style={{
            background: 'linear-gradient(135deg, #fb923c, #f97316, #fbbf24)',
            WebkitBackgroundClip: 'text',
            WebkitTextFillColor: 'transparent',
            backgroundClip: 'text',
          }}>should take seconds, not hours.</span>
        </h1>
        <p className="text-lg text-white/60 max-w-2xl leading-relaxed">
          RoamPlan is an AI-powered travel planning platform built so anyone can explore the world
          confidently — whether you&apos;re a solo adventurer, a family with kids, or a couple hunting
          for the perfect romantic escape.
        </p>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-3 gap-6 mb-16">
        {siteConfig.stats.map((s, i) => (
          <div key={i} className="rounded-2xl p-6 text-center"
            style={{ background: 'rgba(249,115,22,0.06)', border: '1px solid rgba(249,115,22,0.15)' }}>
            <div className="text-3xl font-black text-orange-400 mb-1">{s.stat}</div>
            <div className="text-xs text-white/45">{s.label}</div>
          </div>
        ))}
      </div>

      {/* Sections */}
      <div className="space-y-12">
        <section className="rounded-2xl p-8" style={{ background: 'rgba(255,255,255,0.03)', border: '1px solid rgba(255,255,255,0.07)' }}>
          <h2 className="text-xl font-bold text-white mb-4" style={{ fontFamily: "'Georgia', serif" }}>What We Offer</h2>
          <p className="text-white/60 leading-relaxed mb-4">
            RoamPlan turns a simple destination into a complete day-by-day adventure — morning, afternoon,
            and evening activities, hotel picks, local dining, budget estimates, and 3-day weather
            forecasts. All generated by AI in under 60 seconds. No sign-up required to start.
          </p>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 mt-6">
            {siteConfig.features.map((f, i) => (
              <div key={i} className="flex items-start gap-3 p-3 rounded-xl"
                style={{ background: 'rgba(249,115,22,0.05)', border: '1px solid rgba(249,115,22,0.1)' }}>
                <span className="text-xl flex-shrink-0">{f.icon}</span>
                <div>
                  <div className="text-sm font-semibold text-white">{f.title}</div>
                  <div className="text-xs text-white/45 mt-0.5">{f.desc}</div>
                </div>
              </div>
            ))}
          </div>
        </section>

        <section className="rounded-2xl p-8" style={{ background: 'rgba(255,255,255,0.03)', border: '1px solid rgba(255,255,255,0.07)' }}>
          <h2 className="text-xl font-bold text-white mb-4" style={{ fontFamily: "'Georgia', serif" }}>Built with AI</h2>
          <p className="text-white/60 leading-relaxed">
            We use state-of-the-art AI models — including Groq (Llama), Google Gemini, and Anthropic Claude —
            with an automatic fallback chain so you always get a fast, high-quality itinerary. Our systems
            continuously improve based on user feedback and the latest advances in AI research.
            All AI-generated content is clearly presented as AI output — we believe in transparency.
          </p>
        </section>

        <section className="rounded-2xl p-8" style={{ background: 'rgba(255,255,255,0.03)', border: '1px solid rgba(255,255,255,0.07)' }}>
          <h2 className="text-xl font-bold text-white mb-4" style={{ fontFamily: "'Georgia', serif" }}>Privacy First</h2>
          <p className="text-white/60 leading-relaxed">
            We collect only the data necessary to provide the service. Trip plans are stored locally in
            your browser — not on our servers. We do not sell your data to third parties.
            See our{" "}
            <a href="/privacy" className="text-orange-400 hover:text-orange-300 underline underline-offset-2">
              Privacy Policy
            </a>{" "}
            for full details.
          </p>
        </section>

        <section className="rounded-2xl p-8" style={{ background: 'rgba(255,255,255,0.03)', border: '1px solid rgba(255,255,255,0.07)' }}>
          <h2 className="text-xl font-bold text-white mb-4" style={{ fontFamily: "'Georgia', serif" }}>Get in Touch</h2>
          <p className="text-white/60 leading-relaxed">
            We&apos;d love to hear from you — feedback, bug reports, or partnership enquiries are all welcome.
            Reach us at{" "}
            <a href="mailto:info.siva@gmail.com" className="text-orange-400 hover:text-orange-300 underline underline-offset-2">
              info.siva@gmail.com
            </a>
            {" "}or use our{" "}
            <a href="/contact" className="text-orange-400 hover:text-orange-300 underline underline-offset-2">
              contact page
            </a>.
          </p>
        </section>
      </div>

      {/* CTA */}
      <div className="mt-16 text-center">
        <a href="/#planner"
          className="inline-flex items-center gap-2 px-8 py-4 rounded-xl font-bold text-base text-white transition-all hover:scale-[1.03]"
          style={{ background: 'linear-gradient(135deg, #f97316, #d97706)', boxShadow: '0 8px 30px rgba(249,115,22,0.35)' }}>
          ✈️ Start Planning Free
        </a>
      </div>

      <p className="mt-12 text-center opacity-30 text-xs">© 2026 RoamPlan. All rights reserved.</p>
    </main>
  );
}
